Repository ergebnis/factory-bot, pull requests merged in 2021-01, with the labels that each got.

#493 Fix: Drop support for PHP 7.2
  .github/settings.yml
  .github/workflows/integrate.yaml
  .php_cs
  .php_cs.fixture
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug, merge

#494 Fix: Changelog
  CHANGELOG.md
Labels: bug, merge

#495 Fix: Require at least doctrine/annotations:^1.10.3
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug, dependency, merge

#496 Fix: Require at least doctrine/collections:^1.6.5
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug, dependency, merge

#497 Fix: Reference
  CHANGELOG.md
Labels: bug, merge

#498 Fix: Require at least doctrine/orm:^2.8.0
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug, dependency, merge

#499 Fix: Require at least doctrine/dbal:^2.12.0
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug, dependency, merge

#481 Enhancement: Add support for PHP 8.0
  .github/settings.yml
  .github/workflows/integrate.yaml
  CHANGELOG.md
  composer.json
  composer.lock
Labels: enhancement, merge

#500 Fix: Run 'make static-code-analysis-baseline'
  psalm-baseline.xml
Labels: bug, merge

#504 Enhancement: Synchronize with ergebnis/php-library-template
  .github/settings.yml
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
  README.md
Labels: enhancement, merge

#516 Remove unnecessary polyfills
  composer.json
  composer.lock
Labels: enhancement, merge
