Repository ergebnis/factory-bot, pull requests merged in 2021-12, with the labels that each got.

#682 Fix: Drop support for PHP 7.3
  .github/settings.yml
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug

#686 Fix: Require `composer/package-versions-deprecated`
  composer.json
  composer.lock
Labels: bug, dependency

#681 Fix: Allow composer plugins
  composer.json
  composer.lock
Labels: bug

#689 Fix: Remove `composer/package-versions-deprecated`
  composer.json
  composer.lock
Labels: bug, dependency

#690 Fix: Do not use deprecated `--diff-format` option
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
  Makefile
Labels: bug

#695 Fix: Run `make static-code-analysis-baseline`
  psalm-baseline.xml
Labels: bug

#693 Fix: Rename steps
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
Labels: bug

#696 Fix: Use `Collection` interface
  example/src/Entity/Organization.php
  example/src/Entity/User.php
Labels: bug

#698 Fix: Require `doctrine/persistence:^2.1.0`
  composer.json
  composer.lock
Labels: bug

#697 Fix: Add property type declarations
  example/src/Entity/Avatar.php
  example/src/Entity/CodeOfConduct.php
  example/src/Entity/Organization.php
  example/src/Entity/Project.php
  example/src/Entity/Repository.php
  example/src/Entity/User.php
  example/test/Fixture/Entity/OrganizationDefinitionProvider.php
  phpstan-baseline.neon
  src/Count.php
  src/EntityDefinition.php
  src/FieldDefinition/Closure.php
  src/FieldDefinition/Optional.php
  src/FieldDefinition/Reference.php
  src/FieldDefinition/References.php
  src/FieldDefinition/Sequence.php
  src/FixtureFactory.php
Labels: bug

#694 Enhancement: Use `Php74` rule set
  .php-cs-fixer.fixture.php
  .php-cs-fixer.php
Labels: enhancement

#699 Fix: Use methods instead of deprecated magic properties
  example/test/Fixture/Entity/CodeOfConductDefinitionProvider.php
  example/test/Fixture/Entity/OrganizationDefinitionProvider.php
  example/test/Fixture/Entity/ProjectDefinitionProvider.php
  example/test/Fixture/Entity/RepositoryDefinitionProvider.php
  example/test/Fixture/Entity/UserDefinitionProvider.php
  psalm-baseline.xml
  test/DataProvider/ValueProvider.php
  test/Integration/FixtureFactoryTest.php
  test/Unit/Exception/InvalidFieldNamesTest.php
  test/Unit/FieldDefinition/SequenceTest.php
  test/Unit/FieldDefinitionTest.php
  test/Unit/FixtureFactoryTest.php
Labels: bug

#421 Allow field definitions to be overridden when using reference.
  CHANGELOG.md
  README.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/FieldDefinition.php
  src/FieldDefinition/Reference.php
  src/FieldDefinition/References.php
  test/Unit/FieldDefinition/ReferenceTest.php
  test/Unit/FieldDefinition/ReferencesTest.php
  test/Unit/FieldDefinitionTest.php
Labels: enhancement

#700 Fix: Use dashes instead of asterisks for unordered lists
  CHANGELOG.md
Labels: bug

#702 Enhancement: Allow registering already instantiated entity definition providers
  CHANGELOG.md
  README.md
  phpstan-baseline.neon
  src/FixtureFactory.php
  test/Unit/FixtureFactoryTest.php
Labels: enhancement
